- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes
